eureka:
  instance:
#    hostname: registry
    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.2.169:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

spring:
  rabbitmq:
    host: 192.168.2.156
    username: juhe
    password: juhe123678

  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

authserver:
    port: 5000
    contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.2.169:8060${authserver.contextPath}/current